#!/usr/bin/env python3

import sys
from slor.shared import *

if __name__ == "__main__":

    if len(sys.argv) < 2:
        sys.stderr.write(ROOT_HELP)

    elif sys.argv[1] == "controller":
        import slor.control

        slor.control.run()

    elif sys.argv[1] == "driver":
        import slor.driver

        slor.driver.run()

    elif sys.argv[1] == "analysis":
        import slor.analysis

        slor.analysis.run()

    else:
        sys.stderr.write(ROOT_HELP)
