#!/usr/bin/env python3

from slor.shared import *
import sys

if __name__ == "__main__":

    if len(sys.argv) > 1 and sys.argv[1] == "--version":
        print("SLoR version: {}".format(SLOR_VERSION))
        sys.exit(0)

    if len(sys.argv) < 2:
        sys.stderr.write(ROOT_HELP)

    elif sys.argv[1] == "controller":
        import slor.control

        slor.control.run()

    elif sys.argv[1] == "driver":
        import slor.driver

        slor.driver.run()

    elif sys.argv[1] == "analysis":
        import slor.analysis

        slor.analysis.run()

    else:
        sys.stderr.write(ROOT_HELP)
